"""initial shared schema

Revision ID: 20260831_0001
Revises:
Create Date: 2026-08-31 14:20:23.077862
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260831_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_field_capabilities",
        sa.Column("standard_field_id", sa.String(length=100), nullable=False),
        sa.Column("catalog_version", sa.String(length=32), nullable=False),
        sa.Column("cn_name", sa.String(length=255), nullable=False),
        sa.Column("api_source", sa.String(length=32), nullable=False),
        sa.Column("official_field", sa.String(length=255), nullable=False),
        sa.Column("data_type", sa.String(length=32), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("entity_level", sa.String(length=64), nullable=False),
        sa.Column("query_group", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("standard_field_id", name=op.f("pk_api_field_capabilities")),
    )
    op.create_table(
        "archive_batches",
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("module_id", sa.String(length=100), nullable=False),
        sa.Column("source_table_id", sa.String(length=100), nullable=False),
        sa.Column("target_table_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("cutoff_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("batch_id", name=op.f("pk_archive_batches")),
    )
    op.create_index(
        op.f("ix_archive_batches_module_id"), "archive_batches", ["module_id"], unique=False
    )
    op.create_index(op.f("ix_archive_batches_status"), "archive_batches", ["status"], unique=False)
    op.create_table(
        "channels",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("uploads_playlist_id", sa.String(length=64), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channels")),
    )
    op.create_table(
        "config_cache",
        sa.Column("cache_key", sa.String(length=100), nullable=False),
        sa.Column("version_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("cache_key", name=op.f("pk_config_cache")),
    )
    op.create_index(
        op.f("ix_config_cache_valid_until"), "config_cache", ["valid_until"], unique=False
    )
    op.create_table(
        "feishu_record_bindings",
        sa.Column(
            "binding_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("table_id", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_key", sa.String(length=255), nullable=False),
        sa.Column("record_id", sa.String(length=100), nullable=False),
        sa.Column("last_payload_hash", sa.String(length=64), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("binding_id", name=op.f("pk_feishu_record_bindings")),
        sa.UniqueConstraint(
            "table_id", "entity_type", "entity_key", name="uq_feishu_binding_entity"
        ),
    )
    op.create_index(
        op.f("ix_feishu_record_bindings_table_id"),
        "feishu_record_bindings",
        ["table_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_jobs",
        sa.Column("task_id", sa.String(length=100), nullable=False),
        sa.Column("module_id", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("cursor", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_scheduled_jobs")),
    )
    op.create_index(
        op.f("ix_scheduled_jobs_module_id"), "scheduled_jobs", ["module_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_jobs_next_run_at"), "scheduled_jobs", ["next_run_at"], unique=False
    )
    op.create_table(
        "system_heartbeats",
        sa.Column("instance_id", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("instance_id", name=op.f("pk_system_heartbeats")),
    )
    op.create_index(
        op.f("ix_system_heartbeats_last_seen_at"),
        "system_heartbeats",
        ["last_seen_at"],
        unique=False,
    )
    op.create_table(
        "task_locks",
        sa.Column("lock_key", sa.String(length=150), nullable=False),
        sa.Column("owner_id", sa.String(length=150), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("lock_key", name=op.f("pk_task_locks")),
    )
    op.create_index(op.f("ix_task_locks_expires_at"), "task_locks", ["expires_at"], unique=False)
    op.create_index(op.f("ix_task_locks_owner_id"), "task_locks", ["owner_id"], unique=False)
    op.create_table(
        "task_runs",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("result_counts", sa.JSON(), nullable=True),
        sa.Column("error_type", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_task_runs")),
    )
    op.create_index(op.f("ix_task_runs_status"), "task_runs", ["status"], unique=False)
    op.create_index(op.f("ix_task_runs_task_id"), "task_runs", ["task_id"], unique=False)
    op.create_table(
        "videos",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("privacy_status", sa.String(length=32), nullable=True),
        sa.Column("video_type", sa.String(length=32), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name=op.f("fk_videos_channel_id_channels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
    )
    op.create_index(op.f("ix_videos_channel_id"), "videos", ["channel_id"], unique=False)
    op.create_index(
        "ix_videos_channel_published", "videos", ["channel_id", "published_at"], unique=False
    )
    op.create_index(op.f("ix_videos_published_at"), "videos", ["published_at"], unique=False)
    op.create_table(
        "video_snapshots",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("video_id", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("view_count", sa.BigInteger(), nullable=True),
        sa.Column("like_count", sa.BigInteger(), nullable=True),
        sa.Column("comment_count", sa.BigInteger(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_video_snapshots_video_id_videos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_snapshots")),
        sa.UniqueConstraint("video_id", "observed_at", name="uq_video_snapshot_observation"),
    )
    op.create_index(
        "ix_snapshots_video_observed", "video_snapshots", ["video_id", "observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_video_snapshots_observed_at"), "video_snapshots", ["observed_at"], unique=False
    )
    op.create_index(
        op.f("ix_video_snapshots_video_id"), "video_snapshots", ["video_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_snapshots_video_id"), table_name="video_snapshots")
    op.drop_index(op.f("ix_video_snapshots_observed_at"), table_name="video_snapshots")
    op.drop_index("ix_snapshots_video_observed", table_name="video_snapshots")
    op.drop_table("video_snapshots")
    op.drop_index(op.f("ix_videos_published_at"), table_name="videos")
    op.drop_index("ix_videos_channel_published", table_name="videos")
    op.drop_index(op.f("ix_videos_channel_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_task_runs_task_id"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_status"), table_name="task_runs")
    op.drop_table("task_runs")
    op.drop_index(op.f("ix_task_locks_owner_id"), table_name="task_locks")
    op.drop_index(op.f("ix_task_locks_expires_at"), table_name="task_locks")
    op.drop_table("task_locks")
    op.drop_index(op.f("ix_system_heartbeats_last_seen_at"), table_name="system_heartbeats")
    op.drop_table("system_heartbeats")
    op.drop_index(op.f("ix_scheduled_jobs_next_run_at"), table_name="scheduled_jobs")
    op.drop_index(op.f("ix_scheduled_jobs_module_id"), table_name="scheduled_jobs")
    op.drop_table("scheduled_jobs")
    op.drop_index(op.f("ix_feishu_record_bindings_table_id"), table_name="feishu_record_bindings")
    op.drop_table("feishu_record_bindings")
    op.drop_index(op.f("ix_config_cache_valid_until"), table_name="config_cache")
    op.drop_table("config_cache")
    op.drop_table("channels")
    op.drop_index(op.f("ix_archive_batches_status"), table_name="archive_batches")
    op.drop_index(op.f("ix_archive_batches_module_id"), table_name="archive_batches")
    op.drop_table("archive_batches")
    op.drop_table("api_field_capabilities")
    # ### end Alembic commands ###
