from youtube_feishu_dashboard.module_contracts import ModuleManifest

MODULE_ID = "channel_history"
TASK_ID = "channel-history-daily"

BUSINESS_TABLE_CONFIG_KEYS = {
    "视频主表": "channel_history_video_main_table_id",
    "视频历史数据": "channel_history_video_history_table_id",
    "频道历史数据": "channel_history_channel_history_table_id",
}

DEFAULT_VIDEO_MAIN_MAPPING = {
    "VIDEO_ID": "Video ID",
    "VIDEO_TITLE": "视频标题",
    "VIDEO_PUBLISHED_AT": "发布时间",
    "VIDEO_URL": "视频链接",
    "VIDEO_THUMBNAIL_URL": "缩略图URL",
    "VIDEO_VIEWS_PUBLIC": "当前播放量",
    "VIDEO_LIKES_PUBLIC": "点赞数",
    "VIDEO_COMMENTS_PUBLIC": "评论数",
    "VIDEO_DURATION_TEXT": "视频时长",
    "VIDEO_TYPE": "视频类型",
    "DATA_API_FETCHED_AT_BEIJING": "Data API 数据获取时间（北京时间）",
    "DATA_API_DATA_THROUGH_AT_BEIJING_INFERRED": "Data API 数据截止时间（北京时间）（推定）",
    "ANALYTICS_FETCHED_AT_BEIJING": "Analytics API 数据获取时间（北京时间）",
    "ANALYTICS_DATA_THROUGH_AT_BEIJING": "Analytics API 数据截止时间（北京时间）",
    "VIDEO_VIEWS_LAST_7D_INFERRED": "近7天新增播放量（采样推定）",
    "VIDEO_7D_SAMPLE_START_AT_BEIJING": "近7天采样起点（北京时间）",
    "VIDEO_7D_SAMPLE_END_AT_BEIJING": "近7天采样终点（北京时间）",
    "VIDEO_VIEWS_AT_48H": "发布后48小时播放量",
    "VIDEO_48H_SAMPLE_AGE_MINUTES": "48小时样本发布后分钟数",
    "VIDEO_48H_SAMPLE_AT_BEIJING": "48小时样本采集时间（北京时间）",
}

DEFAULT_VIDEO_HISTORY_MAPPING = {
    "DAILY_VIDEO_RECORD_ID": "唯一键",
    "VIDEO_ID": "Video ID",
    "VIDEO_TITLE": "视频标题",
    "VIDEO_PUBLISHED_AT": "发布时间",
    "VIDEO_TYPE": "视频类型",
    "DAILY_SNAPSHOT_DATE_BEIJING": "记录日期（北京时间）",
    "ANALYTICS_DAY": "统计日期",
    "VIDEO_VIEWS_PUBLIC": "Data API 累计播放量",
    "DAILY_RECORD_TYPE": "记录类型",
    "ANALYTICS_VIEWS": "当日播放量",
    "DATA_API_FETCHED_AT_BEIJING": "Data API 数据获取时间（北京时间）",
    "DATA_API_DATA_THROUGH_AT_BEIJING_INFERRED": "Data API 数据截止时间（北京时间）（推定）",
    "ANALYTICS_FETCHED_AT_BEIJING": "Analytics API 数据获取时间（北京时间）",
    "ANALYTICS_DATA_THROUGH_AT_BEIJING": "Analytics API 数据截止时间（北京时间）",
}

DEFAULT_CHANNEL_HISTORY_MAPPING = {
    "DAILY_CHANNEL_RECORD_ID": "日期Key",
    "ANALYTICS_DAY": "统计日期",
    "CHANNEL_ID": "频道ID",
    "DAILY_SNAPSHOT_DATE_BEIJING": "记录日期（北京时间）",
    "DAILY_RECORD_TYPE": "记录类型",
    "CHANNEL_SUBSCRIBERS_PUBLIC": "订阅人数",
    "CHANNEL_SUBSCRIBER_SNAPSHOT_CHANGE": "订阅快照变化",
    "CHANNEL_VIEWS_PUBLIC": "频道总播放量",
    "CHANNEL_VIDEO_COUNT": "视频数量",
    "ANALYTICS_VIEWS": "当日播放量",
    "ANALYTICS_SUB_GAINED": "新增订阅",
    "ANALYTICS_SUB_LOST": "取消订阅",
    "CHANNEL_CURRENT_SNAPSHOT": "是否最新频道快照",
    "CHANNEL_CURRENT_ANALYTICS_DAY": "是否最新Analytics日",
    "CHANNEL_LONG_VIDEO_VIEWS_PUBLIC": "长视频累计播放量",
    "CHANNEL_LONG_VIDEO_COUNT": "长视频数量",
    "CHANNEL_LONG_VIDEO_DAILY_VIEWS": "长视频当日播放量",
    "SUBSCRIBER_DATA_SOURCE": "订阅数据来源",
    "SUBSCRIBER_DATE_BASIS": "订阅记录日期口径",
    "HISTORY_IMPORT_BATCH_ID": "历史导入批次",
    "DATA_API_FETCHED_AT_BEIJING": "Data API 数据获取时间（北京时间）",
    "DATA_API_DATA_THROUGH_AT_BEIJING_INFERRED": "Data API 数据截止时间（北京时间）（推定）",
    "ANALYTICS_FETCHED_AT_BEIJING": "Analytics API 数据获取时间（北京时间）",
    "ANALYTICS_DATA_THROUGH_AT_BEIJING": "Analytics API 数据截止时间（北京时间）",
    "ANALYTICS_EST_REVENUE": "近28日估算收入（USD）",
}

API_FIELD_IDS = (
    "CHANNEL_ID",
    "CHANNEL_VIEWS_PUBLIC",
    "CHANNEL_SUBSCRIBERS_PUBLIC",
    "CHANNEL_VIDEO_COUNT",
    "VIDEO_ID",
    "VIDEO_TITLE",
    "VIDEO_PUBLISHED_AT",
    "VIDEO_THUMBNAIL_URL",
    "VIDEO_VIEWS_PUBLIC",
    "VIDEO_LIKES_PUBLIC",
    "VIDEO_COMMENTS_PUBLIC",
    "VIDEO_DURATION",
    "VIDEO_LIVE_BROADCAST_CONTENT",
    "ANALYTICS_DAY",
    "ANALYTICS_VIEWS",
    "ANALYTICS_SUB_GAINED",
    "ANALYTICS_SUB_LOST",
    "ANALYTICS_EST_REVENUE",
)

OUTPUT_FIELD_IDS = (
    "VIDEO_URL",
    "VIDEO_TYPE",
    "VIDEO_DURATION_TEXT",
    "DAILY_VIDEO_RECORD_ID",
    "DAILY_CHANNEL_RECORD_ID",
    "DAILY_SNAPSHOT_DATE_BEIJING",
    "DAILY_RECORD_TYPE",
    "VIDEO_VIEWS_LAST_7D_INFERRED",
    "VIDEO_7D_SAMPLE_START_AT_BEIJING",
    "VIDEO_7D_SAMPLE_END_AT_BEIJING",
    "VIDEO_VIEWS_AT_48H",
    "VIDEO_48H_SAMPLE_AGE_MINUTES",
    "VIDEO_48H_SAMPLE_AT_BEIJING",
    "CHANNEL_SUBSCRIBER_SNAPSHOT_CHANGE",
    "CHANNEL_CURRENT_SNAPSHOT",
    "CHANNEL_CURRENT_ANALYTICS_DAY",
    "CHANNEL_LONG_VIDEO_VIEWS_PUBLIC",
    "CHANNEL_LONG_VIDEO_COUNT",
    "CHANNEL_LONG_VIDEO_DAILY_VIEWS",
    "SUBSCRIBER_DATA_SOURCE",
    "SUBSCRIBER_DATE_BASIS",
    "DATA_API_FETCHED_AT_BEIJING",
    "DATA_API_DATA_THROUGH_AT_BEIJING_INFERRED",
    "ANALYTICS_FETCHED_AT_BEIJING",
    "ANALYTICS_DATA_THROUGH_AT_BEIJING",
)

MANIFEST = ModuleManifest(
    module_id=MODULE_ID,
    version="1.0.0",
    cn_name="频道每日统计（长视频）",
    description="每天采集频道基础数据、全部长视频累计播放量及最近已结算统计日。",
    api_field_ids=API_FIELD_IDS,
    output_field_ids=OUTPUT_FIELD_IDS,
    implemented=True,
)
